# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='A caption for the image.', max_length=255, null=True)),
                ('meta', models.CharField(blank=True, help_text='Any extra information for the image.', max_length=255, null=True)),
                ('full_size', models.ForeignKey(blank=True, help_text='A full size image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='The section title.', max_length=255)),
                ('content', wagtail.core.fields.RichTextField(blank=True, help_text='The section content.', null=True)),
                ('image', models.ForeignKey(blank=True, help_text='The section image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('template_path', models.CharField(blank=True, help_text='A path to the template to use to render the page.', max_length=255, null=True)),
                ('body', wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='heading', icon='title')), ('subheading', wagtail.core.blocks.CharBlock(classname='subheading', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock(classname='paragraph', icon='pilcrow')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))), blank=True, help_text='The primary content for the page.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='section',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='webpages.WebPage'),
        ),
        migrations.AddField(
            model_name='images',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webpages.WebPage'),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='A thumbnail image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
